name: Discord PR Announcer
on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK:
        required: true
jobs:
  notify:
    name: Send PR Notification to Discord
    runs-on: ubuntu-latest
    steps:
      - name: Announce Pull Request Event
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ACTION: ${{ github.event.action }}
          MERGED: ${{ github.event.pull_request.merged }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          if [ "$ACTION" = "closed" ]; then
            if [ "$MERGED" = "true" ]; then
              TITLE="✅ [$REPO_NAME] Pull Request Merged"
              STATUS="✅ Merged"
              COLOR=5763719
            else
              TITLE="❌ [$REPO_NAME] Pull Request Closed"
              STATUS="❌ Closed"
              COLOR=15548997
            fi
          elif [ "$ACTION" = "reopened" ]; then
            TITLE="🔄 [$REPO_NAME] Pull Request Reopened"
            STATUS="🔄 Reopened"
            COLOR=16776960
          elif [ "$ACTION" = "ready_for_review" ]; then
            TITLE="👀 [$REPO_NAME] Ready for Review"
            STATUS="👀 Ready"
            COLOR=15105570
          else
            TITLE="🔔 [$REPO_NAME] New Pull Request"
            STATUS="🔔 New"
            COLOR=3447003
          fi

          PAYLOAD=$(jq -n \
            --arg title "$TITLE" \
            --arg prtitle "$PR_TITLE" \
            --arg url "$PR_URL" \
            --arg author "$PR_AUTHOR" \
            --arg branch "$PR_BRANCH" \
            --arg target "$TARGET_BRANCH" \
            --arg status "$STATUS" \
            --arg repo "$REPO_NAME" \
            --argjson color $COLOR \
            '{
              content: ("**" + $title + "**"),
              embeds: [
                {
                  title: ("[" + $repo + "] " + $prtitle),
                  url: $url,
                  color: $color,
                  fields: [
                    {
                      name: "Author",
                      value: $author,
                      inline: true
                    },
                    {
                      name: "Status",
                      value: $status,
                      inline: true
                    },
                    {
                      name: "Branches",
                      value: ("`" + $branch + "` → `" + $target + "`"),
                      inline: false
                    }
                  ],
                  footer: {
                    text: "GitHub Pull Request"
                  },
                  timestamp: (now | todate)
                }
              ]
            }')

          curl -s -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               "$DISCORD_WEBHOOK"
